version: '2'

services:

  web:
    build: .
    ports:
    - "5000:5000"
    environment:
    - DB_HOST=${DB_HOST}
    - DB_NAME=${DB_NAME}
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/app
