version: '2'
services:
  web:
    image: docker.voloshanenko.com/asterisk_cdr 
    restart: unless-stopped
    command: ["python", "app.py"]
    environment:
    - DB_HOST=${DB_HOST}
    - DB_NAME_CDR=${DB_NAME_CDR}
    - DB_NAME_USERS=${DB_NAME_USERS}
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - VIRTUAL_PORT=${VIRTUAL_PORT}
    - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    - ASTERISK_HOST=${ASTERISK_HOST}
    - ASTERISK_AMI_USERNAME=${ASTERISK_AMI_USERNAME}
    - ASTERISK_AMI_PASSWORD=${ASTERISK_AMI_PASSWORD}
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy
