version: '2'
services:
  web:
    build: .
    restart: unless-stopped
    environment:
    - DB_HOST=${DB_HOST}
    - DB_NAME=${DB_NAME}
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - VIRTUAL_PORT=${VIRTUAL_PORT}
    - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy
